"""
Migration ML-03: Training data persistence & horizon fix.

Changes:
  - training_predictions: add `horizon` column, change UNIQUE to (date, split, horizon)
  - Create `models` table
  - Create `training_loss` table

Idempotent: safe to run multiple times.

Usage:
    python db/migrate_ml03.py
    docker compose run --rm app python db/migrate_ml03.py
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy import text
from db.connection import get_engine


def migrate_postgres(conn):
    print("PostgreSQL migration...")

    # training_predictions: add horizon column
    conn.execute(text(
        "ALTER TABLE training_predictions "
        "ADD COLUMN IF NOT EXISTS horizon INT NOT NULL DEFAULT 1"
    ))
    print("  training_predictions.horizon: OK")

    # Drop old unique constraint (name may vary)
    for old_name in [
        "training_predictions_date_split_key",
        "uq_training_predictions_date_split",
    ]:
        try:
            conn.execute(text(
                f"ALTER TABLE training_predictions "
                f"DROP CONSTRAINT IF EXISTS {old_name}"
            ))
        except Exception:
            pass

    # Add new unique constraint
    conn.execute(text(
        "ALTER TABLE training_predictions "
        "DROP CONSTRAINT IF EXISTS training_predictions_date_split_horizon_key"
    ))
    conn.execute(text(
        "ALTER TABLE training_predictions "
        "ADD CONSTRAINT training_predictions_date_split_horizon_key "
        "UNIQUE (date, split, horizon)"
    ))
    print("  training_predictions UNIQUE(date, split, horizon): OK")

    # Create models table
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS models (
            id            SERIAL PRIMARY KEY,
            model_version VARCHAR(255) NOT NULL,
            trial_number  INT          NOT NULL,
            rank_val      INT          NOT NULL,
            is_production BOOLEAN      NOT NULL DEFAULT FALSE,
            hyperparams   TEXT         NOT NULL,
            architecture  TEXT         NOT NULL,
            train_samples INT,
            val_samples   INT,
            test_samples  INT,
            mape_val      FLOAT,
            mape_test     FLOAT,
            mae_test      FLOAT,
            rmse_test     FLOAT,
            artifact_path VARCHAR(512),
            created_at    TIMESTAMP    DEFAULT NOW()
        )
    """))
    print("  models table: OK")

    # Create training_loss table
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS training_loss (
            id            SERIAL PRIMARY KEY,
            model_version VARCHAR(255) NOT NULL,
            trial_number  INT          NOT NULL,
            rank_val      INT          NOT NULL,
            epoch         INT          NOT NULL,
            train_loss    FLOAT,
            val_loss      FLOAT
        )
    """))
    print("  training_loss table: OK")

    # Clear stale data from previous runs (all regenerated by retrain)
    conn.execute(text("DELETE FROM training_predictions"))
    conn.execute(text("DELETE FROM optuna_trials"))
    print("  training_predictions + optuna_trials cleared (retrain to repopulate)")


def migrate_sqlite(conn):
    print("SQLite migration...")

    # Check if horizon column already exists
    cols = [
        row[1] for row in conn.execute(
            text("PRAGMA table_info(training_predictions)")
        ).fetchall()
    ]
    if "horizon" not in cols:
        # Recreate training_predictions with new schema
        conn.execute(text("ALTER TABLE training_predictions RENAME TO training_predictions_old"))
        conn.execute(text("""
            CREATE TABLE training_predictions (
                id            INTEGER PRIMARY KEY AUTOINCREMENT,
                date          TEXT    NOT NULL,
                fsi_actual    REAL,
                fsi_pred      REAL    NOT NULL,
                split         TEXT    NOT NULL,
                horizon       INTEGER NOT NULL DEFAULT 1,
                model_version TEXT    NOT NULL,
                UNIQUE (date, split, horizon)
            )
        """))
        conn.execute(text(
            "INSERT INTO training_predictions "
            "(date, fsi_actual, fsi_pred, split, horizon, model_version) "
            "SELECT date, fsi_actual, fsi_pred, split, 1, model_version "
            "FROM training_predictions_old"
        ))
        conn.execute(text("DROP TABLE training_predictions_old"))
        print("  training_predictions migrated with horizon column")

        # Clear stale rows (retrain to repopulate with proper horizons)
        conn.execute(text("DELETE FROM training_predictions"))
        conn.execute(text("DELETE FROM optuna_trials"))
        print("  training_predictions + optuna_trials cleared (retrain to repopulate)")
    else:
        print("  training_predictions.horizon already exists: skip")

    # models table
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS models (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            model_version TEXT    NOT NULL,
            trial_number  INTEGER NOT NULL,
            rank_val      INTEGER NOT NULL,
            is_production INTEGER NOT NULL DEFAULT 0,
            hyperparams   TEXT    NOT NULL,
            architecture  TEXT    NOT NULL,
            train_samples INTEGER,
            val_samples   INTEGER,
            test_samples  INTEGER,
            mape_val      REAL,
            mape_test     REAL,
            mae_test      REAL,
            rmse_test     REAL,
            artifact_path TEXT,
            created_at    TEXT    DEFAULT (datetime('now'))
        )
    """))
    print("  models table: OK")

    # training_loss table
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS training_loss (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            model_version TEXT    NOT NULL,
            trial_number  INTEGER NOT NULL,
            rank_val      INTEGER NOT NULL,
            epoch         INTEGER NOT NULL,
            train_loss    REAL,
            val_loss      REAL
        )
    """))
    print("  training_loss table: OK")


def main():
    engine = get_engine()
    is_pg = not engine.url.drivername.startswith("sqlite")

    with engine.begin() as conn:
        if is_pg:
            migrate_postgres(conn)
        else:
            migrate_sqlite(conn)

    print("Migration ML-03 complete.")
    print("Next: retrain with  python training/train.py")


if __name__ == "__main__":
    main()
